"""
Curated Indian candidate dataset for the recruitment platform (30 candidates).
Used as a high-quality fallback when Apollo.IO API is unavailable or on Free tier.
All candidates adapted to be Indian tech leaders with phone set to 7889440379.
Contains only candidate-relevant fields matching the Candidate database schema.
"""

from typing import List, Dict, Any

INDIAN_MOCK_CANDIDATES: List[Dict[str, Any]] = [
    {
        "name": "Arjun Sharma",
        "title": "Staff Systems Engineer",
        "company": "Confluent",
        "location": "Bangalore, India (Open to Remote)",
        "phone": "7889440379",
        "email": "arjun.sharma@distributed.dev",
        "linkedin_url": "https://linkedin.com/in/arjun-sharma-systems",
        "profile_url": "https://github.com/arjun-systems",
        "avatar_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go (Golang)", "Kafka", "Distributed Systems", "Kubernetes", "gRPC", "CockroachDB", "Raft", "Python"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Sneha Iyer",
        "title": "Staff Infrastructure Engineer & SRE",
        "company": "Datadog",
        "location": "Bangalore, India (Remote Eligible)",
        "phone": "7889440379",
        "email": "sneha.iyer@infrastructure.io",
        "linkedin_url": "https://linkedin.com/in/sneha-iyer-sre",
        "profile_url": "https://github.com/snehaiyer",
        "avatar_url": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250",
        "skills": ["Kubernetes", "Go", "Kafka", "Prometheus", "Distributed Systems", "gRPC", "FastAPI"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Manav Deshmukh",
        "title": "Principal Backend Systems Architect",
        "company": "Stripe",
        "location": "Mumbai, India",
        "phone": "7889440379",
        "email": "manav.deshmukh@coreeng.com",
        "linkedin_url": "https://linkedin.com/in/manav-deshmukh",
        "profile_url": "https://github.com/manavdeshmukh",
        "avatar_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go", "Rust", "CockroachDB", "Distributed Systems", "Kafka", "Security", "Python"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Esha Reddy",
        "title": "Lead Database Systems Engineer",
        "company": "Cockroach Labs",
        "location": "Hyderabad, India",
        "phone": "7889440379",
        "email": "esha.reddy@storage-lab.org",
        "linkedin_url": "https://linkedin.com/in/esha-reddy",
        "profile_url": "https://github.com/eshareddy",
        "avatar_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go (Golang)", "Distributed Consensus", "Raft", "PostgreSQL", "LSM-Trees", "FastAPI"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Devansh Kapoor",
        "title": "Senior Distributed Platforms Engineer",
        "company": "Netflix",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "devansh.kapoor@streamcore.net",
        "linkedin_url": "https://linkedin.com/in/devansh-kapoor-eng",
        "profile_url": "https://github.com/devanshkapoor",
        "avatar_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go", "Kafka", "Kubernetes", "gRPC", "Cassandra", "PostgreSQL"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Priya Patel",
        "title": "Staff Cloud Systems Architect",
        "company": "Uber",
        "location": "Pune, India",
        "phone": "7889440379",
        "email": "priya.patel@uber-alumni.org",
        "linkedin_url": "https://linkedin.com/in/priya-patel-cloud",
        "profile_url": "https://github.com/priyapatel",
        "avatar_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go (Golang)", "Distributed Systems", "Kafka", "Kubernetes", "Redis", "Docker"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Lakshya Agarwal",
        "title": "Backend Infrastructure Lead",
        "company": "Brex",
        "location": "Gurgaon, India",
        "phone": "7889440379",
        "email": "lakshya.agarwal@fininfra.com",
        "linkedin_url": "https://linkedin.com/in/lakshya-agarwal",
        "profile_url": "https://github.com/lakshyaagarwal",
        "avatar_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go", "PostgreSQL", "Kafka", "Docker", "gRPC", "FastAPI"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Aditya Verma",
        "title": "Lead Fullstack Architect",
        "company": "Razorpay",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "aditya.verma@razorpay.com",
        "linkedin_url": "https://linkedin.com/in/aditya-verma-tech",
        "profile_url": "https://github.com/adityaverma",
        "avatar_url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=250",
        "skills": ["Python", "FastAPI", "React", "Next.js", "PostgreSQL", "Redis", "AWS"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Ananya Nair",
        "title": "Senior Staff Backend Engineer",
        "company": "Flipkart",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "ananya.nair@flipkart.com",
        "linkedin_url": "https://linkedin.com/in/ananya-nair-dev",
        "profile_url": "https://github.com/ananyanair",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250",
        "skills": ["Java", "Spring Boot", "Kafka", "Distributed Systems", "PostgreSQL", "Docker"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Rohan Kulkarni",
        "title": "Principal DevOps & Cloud Architect",
        "company": "Swiggy",
        "location": "Hyderabad, India",
        "phone": "7889440379",
        "email": "rohan.kulkarni@swiggy.in",
        "linkedin_url": "https://linkedin.com/in/rohan-kulkarni-sre",
        "profile_url": "https://github.com/rohankulkarni",
        "avatar_url": "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&q=80&w=250",
        "skills": ["Kubernetes", "Terraform", "AWS", "Docker", "Prometheus", "CI/CD", "Go"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Pooja Hegde",
        "title": "Lead Software Engineer - Payments Core",
        "company": "PhonePe",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "pooja.hegde@phonepe.com",
        "linkedin_url": "https://linkedin.com/in/pooja-hegde-eng",
        "profile_url": "https://github.com/poojahegde",
        "avatar_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=250",
        "skills": ["Java", "Go", "Kafka", "MySQL", "Redis", "Microservices", "Kubernetes"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Vikram Malhotra",
        "title": "Staff Platform Engineer",
        "company": "CRED",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "vikram.malhotra@cred.club",
        "linkedin_url": "https://linkedin.com/in/vikram-malhotra-infra",
        "profile_url": "https://github.com/vikrammalhotra",
        "avatar_url": "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go", "Python", "Kubernetes", "Kafka", "PostgreSQL", "AWS", "gRPC"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Kavita Rao",
        "title": "Senior Staff Data Platform Engineer",
        "company": "Zomato",
        "location": "Gurgaon, India",
        "phone": "7889440379",
        "email": "kavita.rao@zomato.com",
        "linkedin_url": "https://linkedin.com/in/kavita-rao-data",
        "profile_url": "https://github.com/kavitarao",
        "avatar_url": "https://images.unsplash.com/photo-1534751516642-a171edd2521d?auto=format&fit=crop&q=80&w=250",
        "skills": ["Python", "Spark", "Kafka", "Airflow", "Snowflake", "AWS", "FastAPI"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Nikhil Singhania",
        "title": "Senior Backend Architect",
        "company": "Zerodha",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "nikhil.s@zerodha.tech",
        "linkedin_url": "https://linkedin.com/in/nikhil-singhania-dev",
        "profile_url": "https://github.com/nikhilsinghania",
        "avatar_url": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go (Golang)", "Python", "PostgreSQL", "Redis", "Kafka", "WebSockets"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Divya Nambiar",
        "title": "Staff Fullstack Engineer",
        "company": "Postman",
        "location": "Bangalore, India (Remote)",
        "phone": "7889440379",
        "email": "divya.nambiar@postman.com",
        "linkedin_url": "https://linkedin.com/in/divya-nambiar-code",
        "profile_url": "https://github.com/divyanambiar",
        "avatar_url": "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&q=80&w=250",
        "skills": ["TypeScript", "Node.js", "React", "FastAPI", "PostgreSQL", "Docker", "GraphQL"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Karan Mehra",
        "title": "Lead Distributed Systems Engineer",
        "company": "BrowserStack",
        "location": "Mumbai, India",
        "phone": "7889440379",
        "email": "karan.mehra@browserstack.com",
        "linkedin_url": "https://linkedin.com/in/karan-mehra-sys",
        "profile_url": "https://github.com/karanmehra",
        "avatar_url": "https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go", "Docker", "Kubernetes", "Linux Kernel", "gRPC", "Kafka", "Python"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Meera Joshi",
        "title": "Staff SRE & Observability Lead",
        "company": "Meesho",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "meera.joshi@meesho.com",
        "linkedin_url": "https://linkedin.com/in/meera-joshi-sre",
        "profile_url": "https://github.com/meerajoshi",
        "avatar_url": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=250",
        "skills": ["Kubernetes", "Terraform", "Prometheus", "Grafana", "Go", "AWS", "Python"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Sameer Bansal",
        "title": "Principal Software Engineer - Core Engine",
        "company": "Groww",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "sameer.bansal@groww.in",
        "linkedin_url": "https://linkedin.com/in/sameer-bansal-fintech",
        "profile_url": "https://github.com/sameerbansal",
        "avatar_url": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250",
        "skills": ["Java", "Go", "PostgreSQL", "Kafka", "Spring Boot", "Docker", "Microservices"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Ritu Sen",
        "title": "Staff Frontend Architect",
        "company": "Atlassian",
        "location": "Bangalore, India (Remote)",
        "phone": "7889440379",
        "email": "ritu.sen@atlassian.com",
        "linkedin_url": "https://linkedin.com/in/ritu-sen-frontend",
        "profile_url": "https://github.com/ritusendata",
        "avatar_url": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=250",
        "skills": ["React", "TypeScript", "Next.js", "GraphQL", "Node.js", "TailwindCSS", "Jest"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Varun Bhattacharya",
        "title": "Senior Staff Infrastructure Architect",
        "company": "InMobi",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "varun.b@inmobi.com",
        "linkedin_url": "https://linkedin.com/in/varun-bhattacharya",
        "profile_url": "https://github.com/varunbhattacharya",
        "avatar_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go", "Kafka", "Aerospike", "Kubernetes", "Distributed Systems", "C++"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Shreya Mukherjee",
        "title": "Lead Backend & Microservices Engineer",
        "company": "Zepto",
        "location": "Mumbai, India",
        "phone": "7889440379",
        "email": "shreya.m@zeptonow.com",
        "linkedin_url": "https://linkedin.com/in/shreya-mukherjee-dev",
        "profile_url": "https://github.com/shreyamukherjee",
        "avatar_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250",
        "skills": ["Python", "FastAPI", "Go", "PostgreSQL", "Redis", "Kafka", "Docker"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Tarun Khanna",
        "title": "Principal Distributed Storage Engineer",
        "company": "Microsoft",
        "location": "Hyderabad, India",
        "phone": "7889440379",
        "email": "tarun.khanna@microsoft.com",
        "linkedin_url": "https://linkedin.com/in/tarun-khanna-storage",
        "profile_url": "https://github.com/tarunkhanna",
        "avatar_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250",
        "skills": ["C++", "Rust", "Distributed Systems", "Azure", "Raft", "Linux Kernel"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Swati Choudhury",
        "title": "Staff Cloud Security & DevOps Engineer",
        "company": "Ola Electric",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "swati.c@olaelectric.com",
        "linkedin_url": "https://linkedin.com/in/swati-choudhury-sec",
        "profile_url": "https://github.com/swatichoudhury",
        "avatar_url": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=250",
        "skills": ["AWS", "Kubernetes", "Terraform", "Vault", "Docker", "Python", "Go"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Gaurav Aggarwal",
        "title": "Senior Staff Software Engineer",
        "company": "Google",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "gaurav.aggarwal@google.com",
        "linkedin_url": "https://linkedin.com/in/gaurav-aggarwal-google",
        "profile_url": "https://github.com/gauravaggarwal",
        "avatar_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go", "C++", "Distributed Systems", "Borg", "Spanner", "gRPC", "Python"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Anjali Deshpande",
        "title": "Lead Fullstack & API Architect",
        "company": "Juspay",
        "location": "Bangalore, India",
        "phone": "7889440379",
        "email": "anjali.d@juspay.in",
        "linkedin_url": "https://linkedin.com/in/anjali-deshpande-api",
        "profile_url": "https://github.com/anjalideshpande",
        "avatar_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250",
        "skills": ["Haskell", "Rust", "Python", "FastAPI", "React", "PostgreSQL", "Docker"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Prateek Rawat",
        "title": "Staff Platform Infrastructure Engineer",
        "company": "Urban Company",
        "location": "Gurgaon, India",
        "phone": "7889440379",
        "email": "prateek.rawat@urbancompany.com",
        "linkedin_url": "https://linkedin.com/in/prateek-rawat-infra",
        "profile_url": "https://github.com/prateekrawat",
        "avatar_url": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=250",
        "skills": ["Node.js", "Go", "Kubernetes", "Kafka", "PostgreSQL", "Redis", "AWS"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Nisha Sundaram",
        "title": "Staff Data Infrastructure Engineer",
        "company": "Delhivery",
        "location": "Gurgaon, India (Remote)",
        "phone": "7889440379",
        "email": "nisha.sundaram@delhivery.com",
        "linkedin_url": "https://linkedin.com/in/nisha-sundaram-data",
        "profile_url": "https://github.com/nishasundaram",
        "avatar_url": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250",
        "skills": ["Python", "Spark", "Kafka", "ClickHouse", "Kubernetes", "FastAPI", "AWS"],
        "source": "DEMO",
        "consent_status": "granted",
    },
    {
        "name": "Harshvardhan Jain",
        "title": "Principal Systems Architect",
        "company": "Amazon AWS",
        "location": "Hyderabad, India",
        "phone": "7889440379",
        "email": "harsh.jain@amazon.com",
        "linkedin_url": "https://linkedin.com/in/harshvardhan-jain-aws",
        "profile_url": "https://github.com/harshjain",
        "avatar_url": "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=250",
        "skills": ["Java", "Go", "DynamoDB", "Distributed Systems", "AWS", "gRPC", "Docker"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Tanvi Kapoor",
        "title": "Lead Software Engineer - Core Platform",
        "company": "Freshworks",
        "location": "Chennai, India",
        "phone": "7889440379",
        "email": "tanvi.kapoor@freshworks.com",
        "linkedin_url": "https://linkedin.com/in/tanvi-kapoor-tech",
        "profile_url": "https://github.com/tanvikapoor",
        "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
        "skills": ["Ruby on Rails", "Go", "Kafka", "MySQL", "Redis", "AWS", "FastAPI"],
        "source": "DEMO",
        "consent_status": "pending",
    },
    {
        "name": "Siddharth Chawla",
        "title": "Staff High-Throughput Systems Engineer",
        "company": "Dream11",
        "location": "Mumbai, India",
        "phone": "7889440379",
        "email": "siddharth.c@dream11.com",
        "linkedin_url": "https://linkedin.com/in/siddharth-chawla-eng",
        "profile_url": "https://github.com/siddharthchawla",
        "avatar_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=250",
        "skills": ["Go", "Kafka", "Aerospike", "Kubernetes", "Redis", "Cassandra", "PostgreSQL"],
        "source": "DEMO",
        "consent_status": "granted",
    },
]


def get_mock_candidates_for_job(
    skills: List[str] = None,
    location: str = None,
    title: str = None,
    limit: int = 30,
) -> List[Dict[str, Any]]:
    """
    Returns Indian candidate profiles with phone 7889440379.
    Merges any job-specific skills and returns only candidate-relevant fields.
    Supports up to 30 distinct candidates.
    """
    max_limit = min(max(limit, 1), len(INDIAN_MOCK_CANDIDATES))
    results: List[Dict[str, Any]] = []

    for cand in INDIAN_MOCK_CANDIDATES[:max_limit]:
        item = dict(cand)
        # Merge job skills with candidate skills if specified
        if skills:
            item["skills"] = list(dict.fromkeys(item.get("skills", []) + skills))
        # Ensure phone number is strictly 7889440379 and source is DEMO
        item["phone"] = "7889440379"
        item["source"] = "DEMO"
        results.append(item)

    return results
