"""drop calls, answers, and scores tables

Revision ID: 50b1b0131d46
Revises: ee3ba8bcd07c
Create Date: 2026-09-06 15:57:00.800143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b1b0131d46'
down_revision: Union[str, Sequence[str], None] = 'ee3ba8bcd07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('score')
    op.drop_table('callsession')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('call_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extracted_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], name=op.f('answer_call_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('answer_pkey'))
    )
    op.create_table('callsession',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transcript', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recording_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('external_call_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('callsession_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('callsession_pkey'))
    )
    op.create_table('score',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('call_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reasoning', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['callsession.id'], name=op.f('score_call_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('score_pkey'))
    )
    # ### end Alembic commands ###
