"""update job schema remove company_id pass_criteria add seniority location experience skills

Revision ID: a20a9dce70e9
Revises: 89b0ba088fb0
Create Date: 2026-09-06 00:38:14.721047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a20a9dce70e9'
down_revision: Union[str, Sequence[str], None] = '89b0ba088fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('target_seniority_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('target_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('experience_required', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('required_skills', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_job_company_id'), table_name='job')
    op.drop_column('job', 'pass_criteria')
    op.drop_column('job', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('pass_criteria', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_job_company_id'), 'job', ['company_id'], unique=False)
    op.drop_column('job', 'required_skills')
    op.drop_column('job', 'experience_required')
    op.drop_column('job', 'target_location')
    op.drop_column('job', 'target_seniority_level')
    # ### end Alembic commands ###
