"""add fields to candidate table

Revision ID: d5276d984c56
Revises: a20a9dce70e9
Create Date: 2026-09-06 01:32:15.796860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5276d984c56'
down_revision: Union[str, Sequence[str], None] = 'a20a9dce70e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate', sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate', sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate', sa.Column('profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidate', sa.Column('skills', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'skills')
    op.drop_column('candidate', 'avatar_url')
    op.drop_column('candidate', 'profile_url')
    op.drop_column('candidate', 'linkedin_url')
    op.drop_column('candidate', 'location')
    op.drop_column('candidate', 'company')
    op.drop_column('candidate', 'title')
    # ### end Alembic commands ###
